In [14]:
import pandas as pd
weather = pd.read_csv("weather_2019_upscale.csv",header=0,index_col=0)
nov = pd.read_csv("november_weather.csv",header=0)

In [5]:
weather

,Year,m,d,Time,Cloud amount (1/8),Relative humidity (%),Precipitation intensity (mm/h),Air temperature (degC),Wind speed (m/s),Timestamp
0,2019,4,1,00:00,0.0,77.0,0.0,-0.1,4.6,2019-04-01 00:00:00
1,2019,4,1,00:05,0.0,77.0,0.0,-0.1,4.6,2019-04-01 00:05:00
2,2019,4,1,00:10,0.0,77.0,0.0,0.0,4.8,2019-04-01 00:10:00
3,2019,4,1,00:15,0.0,77.0,0.0,0.0,4.8,2019-04-01 00:15:00
4,2019,4,1,00:20,0.0,77.0,0.0,0.1,5.1,2019-04-01 00:20:00
...,...,...,...,...,...,...,...,...,...,...
61627,2019,10,31,23:35,0.0,95.0,0.0,0.3,5.3,2019-10-31 23:35:00
61628,2019,10,31,23:40,0.0,94.0,0.0,0.4,5.3,2019-10-31 23:40:00
61629,2019,10,31,23:45,0.0,94.0,0.0,0.4,5.3,2019-10-31 23:45:00
61630,2019,10,31,23:50,0.0,94.0,0.0,0.1,4.6,2019-10-31 23:50:00
61631,2019,10,31,23:55,0.0,94.0,0.0,0.1,4.6,2019-10-31 23:55:00

In [11]:
nov

,Year,m,d,Time,Time zone,Cloud amount (1/8),Relative humidity (%),Precipitation intensity (mm/h),Air temperature (degC),Wind speed (m/s)
0,2019,10,31,00:00,UTC,1,93,0.0,2.4,3.1
1,2019,10,31,00:10,UTC,1,93,0.0,2.7,3.7
2,2019,10,31,00:20,UTC,3,92,0.0,3.4,5.4
3,2019,10,31,00:30,UTC,5,92,0.0,3.6,5.2
4,2019,10,31,00:40,UTC,7,91,0.0,3.6,4.6
...,...,...,...,...,...,...,...,...,...,...
859,2019,11,5,23:10,UTC,1,39,0.0,-1.9,6.3
860,2019,11,5,23:20,UTC,1,40,0.0,-2.0,7.1
861,2019,11,5,23:30,UTC,1,42,0.0,-2.3,6.6
862,2019,11,5,23:40,UTC,1,41,0.0,-2.2,7.5
863,2019,11,5,23:50,UTC,1,43,0.0,-2.5,7.0

In [15]:
nov.drop(len(nov) - 1,inplace=True)
nov.drop(columns=['Time zone'],inplace=True)
nov.drop(nov.index[nov['m']==10].tolist(),inplace=True)

In [16]:
nov

,Year,m,d,Time,Cloud amount (1/8),Relative humidity (%),Precipitation intensity (mm/h),Air temperature (degC),Wind speed (m/s)
144,2019,11,1,00:00,0,95,0.0,0.0,4.1
145,2019,11,1,00:10,0,94,0.0,0.2,4.5
146,2019,11,1,00:20,0,94,0.0,0.0,4.8
147,2019,11,1,00:30,0,94,0.0,0.0,4.7
148,2019,11,1,00:40,0,94,0.0,0.1,4.7
...,...,...,...,...,...,...,...,...,...
859,2019,11,5,23:10,1,39,0.0,-1.9,6.3
860,2019,11,5,23:20,1,40,0.0,-2.0,7.1
861,2019,11,5,23:30,1,42,0.0,-2.3,6.6
862,2019,11,5,23:40,1,41,0.0,-2.2,7.5
863,2019,11,5,23:50,1,43,0.0,-2.5,7.0

In [17]:
data = nov
print(data['Cloud amount (1/8)'].isna().sum(), 'NaNs in Cloud amount')
print(data['Precipitation intensity (mm/h)'].isna().sum(), 'NaNs in Precipitation intensity')
print(data['Relative humidity (%)'].isna().sum(), 'NaNs in Relative humidity')
print(data['Air temperature (degC)'].isna().sum(), 'NaNs in Air temperature')
print(data['Wind speed (m/s)'].isna().sum(), 'NaNs in Wind speed')

0 NaNs in Cloud amount
0 NaNs in Precipitation intensity
0 NaNs in Relative humidity
0 NaNs in Air temperature
0 NaNs in Wind speed

In [18]:
data_5min = []

for i in range(len(data)):
    data_5min.append(data.iloc[i])
    data_5min.append(data.iloc[i])


index_5min = list(range(len(data_5min)))

data_5min = pd.DataFrame(data_5min, index=index_5min)

for i in range(1, len(data_5min), 2):
    data_5min.loc[i, 'Time'] = data_5min['Time'][i][:-1] + '5'

data_5min

,Year,m,d,Time,Cloud amount (1/8),Relative humidity (%),Precipitation intensity (mm/h),Air temperature (degC),Wind speed (m/s)
0,2019,11,1,00:00,0,95,0.0,0.0,4.1
1,2019,11,1,00:05,0,95,0.0,0.0,4.1
2,2019,11,1,00:10,0,94,0.0,0.2,4.5
3,2019,11,1,00:15,0,94,0.0,0.2,4.5
4,2019,11,1,00:20,0,94,0.0,0.0,4.8
...,...,...,...,...,...,...,...,...,...
1435,2019,11,5,23:35,1,42,0.0,-2.3,6.6
1436,2019,11,5,23:40,1,41,0.0,-2.2,7.5
1437,2019,11,5,23:45,1,41,0.0,-2.2,7.5
1438,2019,11,5,23:50,1,43,0.0,-2.5,7.0
1439,2019,11,5,23:55,1,43,0.0,-2.5,7.0

In [19]:
months = [str(i).zfill(2) for i in data_5min['m']]
days = [str(i).zfill(2) for i in data_5min['d']]

timestamps = [str(data_5min['Year'][i]) + str(months[i]) + str(days[i]) + data_5min['Time'][i][:2] 
              + data_5min['Time'][i][3:] for i in range(len(data_5min))]

# timestamps = [str(data['Year'][i]) + '/' + str(months[i]) + '/' + str(days[i]) + ' ' + str(data['Time'][i]) + ':00'
#               for i in range(len(data))]

data_5min['Timestamp'] = pd.to_datetime(timestamps)
data_5min

,Year,m,d,Time,Cloud amount (1/8),Relative humidity (%),Precipitation intensity (mm/h),Air temperature (degC),Wind speed (m/s),Timestamp
0,2019,11,1,00:00,0,95,0.0,0.0,4.1,2019-11-01 00:00:00
1,2019,11,1,00:05,0,95,0.0,0.0,4.1,2019-11-01 00:05:00
2,2019,11,1,00:10,0,94,0.0,0.2,4.5,2019-11-01 00:10:00
3,2019,11,1,00:15,0,94,0.0,0.2,4.5,2019-11-01 00:15:00
4,2019,11,1,00:20,0,94,0.0,0.0,4.8,2019-11-01 00:20:00
...,...,...,...,...,...,...,...,...,...,...
1435,2019,11,5,23:35,1,42,0.0,-2.3,6.6,2019-11-05 23:35:00
1436,2019,11,5,23:40,1,41,0.0,-2.2,7.5,2019-11-05 23:40:00
1437,2019,11,5,23:45,1,41,0.0,-2.2,7.5,2019-11-05 23:45:00
1438,2019,11,5,23:50,1,43,0.0,-2.5,7.0,2019-11-05 23:50:00
1439,2019,11,5,23:55,1,43,0.0,-2.5,7.0,2019-11-05 23:55:00

In [21]:
data = pd.concat([weather, data_5min], ignore_index=True)
data

,Year,m,d,Time,Cloud amount (1/8),Relative humidity (%),Precipitation intensity (mm/h),Air temperature (degC),Wind speed (m/s),Timestamp
0,2019,4,1,00:00,0.0,77.0,0.0,-0.1,4.6,2019-04-01 00:00:00
1,2019,4,1,00:05,0.0,77.0,0.0,-0.1,4.6,2019-04-01 00:05:00
2,2019,4,1,00:10,0.0,77.0,0.0,0.0,4.8,2019-04-01 00:10:00
3,2019,4,1,00:15,0.0,77.0,0.0,0.0,4.8,2019-04-01 00:15:00
4,2019,4,1,00:20,0.0,77.0,0.0,0.1,5.1,2019-04-01 00:20:00
...,...,...,...,...,...,...,...,...,...,...
63067,2019,11,5,23:35,1.0,42.0,0.0,-2.3,6.6,2019-11-05 23:35:00
63068,2019,11,5,23:40,1.0,41.0,0.0,-2.2,7.5,2019-11-05 23:40:00
63069,2019,11,5,23:45,1.0,41.0,0.0,-2.2,7.5,2019-11-05 23:45:00
63070,2019,11,5,23:50,1.0,43.0,0.0,-2.5,7.0,2019-11-05 23:50:00
63071,2019,11,5,23:55,1.0,43.0,0.0,-2.5,7.0,2019-11-05 23:55:00

In [22]:
data.to_csv('weather_2019_upscale.csv')